/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Head: typeof import('@inertiajs/vue3')['Head']
    Link: typeof import('@inertiajs/vue3')['Link']
    ModalLink: typeof import('@inertiaui/modal-vue')['ModalLink']
    PrimeAutoComplete: typeof import('primevue/autocomplete')['default']
    PrimeBadge: typeof import('primevue/badge')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCard: typeof import('primevue/card')['default']
    PrimeCheckbox: typeof import('primevue/checkbox')['default']
    PrimeColorPicker: typeof import('primevue/colorpicker')['default']
    PrimeDatePicker: typeof import('primevue/datepicker')['default']
    PrimeEditor: typeof import('primevue/editor')['default']
    PrimeFileUpload: typeof import('primevue/fileupload')['default']
    PrimeIconField: typeof import('primevue/iconfield')['default']
    PrimeInputIcon: typeof import('primevue/inputicon')['default']
    PrimeInputMask: typeof import('primevue/inputmask')['default']
    PrimeInputNumber: typeof import('primevue/inputnumber')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimeMessage: typeof import('primevue/message')['default']
    PrimeMultiSelect: typeof import('primevue/multiselect')['default']
    PrimePassword: typeof import('primevue/password')['default']
    PrimeProgressBar: typeof import('primevue/progressbar')['default']
    PrimeRadioButton: typeof import('primevue/radiobutton')['default']
    PrimeRadioButtonGroup: typeof import('primevue/radiobuttongroup')['default']
    PrimeRating: typeof import('primevue/rating')['default']
    PrimeSelect: typeof import('primevue/select')['default']
    PrimeSlider: typeof import('primevue/slider')['default']
    PrimeTextarea: typeof import('primevue/textarea')['default']
    PrimeTreeSelect: typeof import('primevue/treeselect')['default']
  }
  export interface GlobalDirectives {
    FocusTrap: typeof import('primevue/focustrap')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
